#!/bin/bash
# Created by http://www.vps-murah.net
# Remodified by WaGo-G

MYIP=`ifconfig eth0 | awk 'NR==2 {print $2}'`
MYIP2="s/xxxxxxxxx/$MYIP/g";

if [[ $USER != 'root' ]]; then
	echo "Oops! root privileges needed"
	exit
fi
while :
do
	clear
	echo " "
	echo " "
	echo "-----------------------------------------"
	echo "           Download OVPN Configs         "
	echo "-----------------------------------------"
	echo "Welcome to OVPN configs download section!"
	echo "Looking for OpenVpn TCP config?"
	echo " "
	echo "Download it on http://$MYIP/wago-tcp.ovpn"
	echo " "
	echo "     [ MENU ]"
	echo "1. Go Back"
	read -p "Type 1 to go back : " option2
	case $option2 in
		1)
		clear
		exit
		;;
	esac
done
cd
