#!/bin/bash
# Created by http://www.vps-murah.net
# Remodified by reputation

if [[ $USER != 'root' ]]; then
	echo "Oops! root privileges needed"
	exit
fi
while :
do
	clear
	echo " "
	echo " "
	echo "-----------------------------------------"
	echo "           Download OVPN Configs         "
	echo "-----------------------------------------"
	echo "Welcome to OVPN configs download section!"
	echo "Looking for OpenVpn configs?"
	echo "Download configs below"
	echo " "
	echo "     [ MENU ]"
	echo "1. Download OpenVPN TCP (Port: 1194)"
	echo "2. Download OpenVPN SSL (Port: 443)"
	echo "3. Download OpenVPN Package (TCP/SSL/stunnel.conf)"
	echo "4. Go Back"
	read -p "Choose from 1 to 4 : " option2
	case $option2 in
		1)
		clear
		cd
		ovpntcp
		;;
		2)
		clear
		cd
		ovpnssl
		;;
		3)
		clear
		cd /home/vps/public_html
		rm -rf openvpn.zip
		rm -rf configs.zip
		clear
		zip configs.zip wago-tcp.ovpn wago-openvpn-ssl.ovpn stunnel.conf
		ovpnzip
		;;
		4)
		clear
		exit
		;;
	esac
done
cd
