#!/bin/bash
# created by WaGo-G

# initializing var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";

if [[ $USER != 'root' ]]; then
	echo "Oops! root privileges needed"
	exit
fi
while :
do
	clear
	echo " "
	echo " "
	echo "-----------------------------------------"
	echo "          Change Privoxy Privacy        "
	echo "-----------------------------------------"
	echo "Set your privoxy as public or private"
	echo "Choose your choice below"
	echo " "
	echo "    [ MENU ]"
	echo "1. Allow anyone to use your privoxy"
	echo "2. Only me can use my privoxy"
	echo "3. Go back"
	read -p "Choose from 1 to 3 : " option2
	case $option2 in
		1)
		clear
		rm /etc/privoxy/config
		echo 1 > /etc/privoxy/config
		cat > /etc/privoxy/config <<-END
		user-manual /usr/share/doc/privoxy/user-manual
		confdir /etc/privoxy
		logdir /var/log/privoxy
		filterfile default.filter
		logfile logfile
		listen-address 0.0.0.0:8020
		listen-address [::1]:8020
		toggle 1
		enable-remote-toggle 0
		enable-remote-http-toggle 0
		enable-edit-actions 0
		enforce-blocks 0
		buffer-limit 4096
		enable-proxy-authentication-forwarding 1
		forwarded-connect-retries 1
		accept-intercepted-requests 1
		allow-cgi-request-crunching 1
		split-large-forms 0
		keep-alive-timeout 5
		tolerate-pipelining 1
		socket-timeout 300
		END
		clear
		service privoxy restart
		clear
		echo "Your privoxy are now set to public"
		sleep 5
		clear
		;;
		2)
		clear
		rm /etc/privoxy/config
		echo 1 > /etc/privoxy/config
		cat > /etc/privoxy/config <<-END
		user-manual /usr/share/doc/privoxy/user-manual
		confdir /etc/privoxy
		logdir /var/log/privoxy
		filterfile default.filter
		logfile logfile
		listen-address 0.0.0.0:8020
		listen-address [::1]:8020
		toggle 1
		enable-remote-toggle 0
		enable-remote-http-toggle 0
		enable-edit-actions 0
		enforce-blocks 0
		buffer-limit 4096
		enable-proxy-authentication-forwarding 1
		forwarded-connect-retries 1
		accept-intercepted-requests 1
		allow-cgi-request-crunching 1
		split-large-forms 0
		keep-alive-timeout 5
		tolerate-pipelining 1
		socket-timeout 300
		permit-access 0.0.0.0/0 $MYIP
		END
		clear
		service privoxy restart
		clear
		echo "Your privoxy are now set to private"
		sleep 5
		clear
		;;
		3)
		clear
		exit
		;;
	esac
done
cd
