#!/bin/bash
# Created by http://www.vps-murah.net
# Remodified by WaGo-G

# initializing var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";

if [[ $USER != 'root' ]]; then
	echo "Oops! root privileges needed"
	exit
fi
while :
do
	clear
	echo ""
	echo ""
	echo "-----------------------------------------"
	echo "            Smart Squid       "
	echo "-----------------------------------------"
	echo ""
	echo "INFO: You must stop your squid first before installation"
	echo "If you can't download client.ovpn then"
	echo "change the nginx port to 81"
	echo "The file should be like this http://$MYIP:81/client.ovpn"
	echo "(if you changed the nginx port to 81)"
	echo ""
	echo "This tool can help you to work the TU50+ Promo OVPN"
	echo ""
	echo "     [ MENU ]"
	echo "1. Stop Squid"
	echo "2. Install now"
	echo "3. Change Nginx Port to 81"
	echo "4. Change Nginx Port to 80"
	echo "5. Go back"
	read -p "Choose from 1 to 5 : " option2
	case $option2 in
		1)
		clear
		cd
		echo "Stopping Squid..."
		service squid stop
		clear
		echo "Stopping Squid... OK!"
		sleep 2
		;;
		2)
		clear
		cd
		bash -c "$(wget -qO- https://raw.githubusercontent.com/wagovps/OvpnSsl/master/tool/ss)"
		;;
		3)
		clear
		sed -i '1,30 s/80/81/g' /etc/nginx/sites-enabled/default
		service nginx restart
		clear
		echo "Success! Rebooting server..."
		echo "NGINX Port is now changed to port 81 successfully!"
		echo "Visit http://$MYIP:81 now!"
		sleep 5
		;;
		4)
		clear
		sed -i '1,30 s/81/80/g' /etc/nginx/sites-enabled/default
		service nginx restart
		clear
		echo "NGINX Port is now changed to port 80 successfully!"
		echo "Visit http://$MYIP:80 now!"
		sleep 5
		;;
		5)
		clear
		exit
		;;
	esac
done
cd
