#!/bin/bash
# Created by http://www.vps-murah.net
# Remodified by WaGo-G

if [[ $USER != 'root' ]]; then
	echo "Oops! root privileges needed"
	exit
fi
while :
do
	clear
	echo " "
	echo " "
	echo "----------------------------------------------"
	echo "        ShadowsocksR Net Stable Fixer    "
	echo "----------------------------------------------"
	echo "[ ok ] SSR tweak"
	echo "[ ok ] Lag optimize"
	echo "[ ok ] Connections stable"
	echo "[ ok ] SSR will not sleep"
	echo "[ ok ] Setup completion"
	echo " "
	echo "INFO: To check your connection type head /var/log/shadowsocks-auto.log"
	echo " "
	echo " [ MENU ]"
	echo "1. Go Back"
	read -p "Type 1 to go back : " option2
	case $option2 in
		1)
		clear
		exit
		;;
	esac
done
cd
